kind: Job
apiVersion: batch/v1
metadata:
  name: human-eval-deployment-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: human-eval-benchmark
          image: "quay.io/kruizehub/human-eval-deployment:v1"
          imagePullPolicy: Always
          env:
            - name: num_prompts
              value: '500'
            - name: duration_in_seconds
              value: '1800'
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "2"
              nvidia.com/gpu: 1
          volumeMounts:
            - name: cache-volume
              mountPath: /.cache/huggingface
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: human-eval-pvc
