apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: renaissance
  labels:
    team: renaissance-frontend
spec:
  selector:
    matchLabels:
        app: renaissance-app
  endpoints:
    - port: renaissance-port
      path: '/metrics'
