apiVersion: "recommender.com/v1"
kind: Autotune
metadata:
  name: "quarkus-resteasy-autotune"
  namespace: "default"
spec:
  slo:
    objective_function: "request_sum/request_count"
    slo_class: "response_time"
    direction: "minimize"
    function_variables:
    - name: "request_sum"
      query: rate(http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/db",}[1m])
      datasource: "prometheus"
      value_type: "double"
    - name: "request_count"
      query: rate(http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/db",}[1m])
      datasource: "prometheus"
      value_type: "double"
  mode: "show"
  selector:
    matchLabel: "app.kubernetes.io/name"
    matchLabelValue: "quarkus-resteasy-deployment"
    matchRoute: ""
    matchURI: ""
    matchService: ""
